workflows:
  ios_sien_ca_unsigned:
    name: Sien Ca iOS (Unsigned for Sideloadly)
    max_build_duration: 30
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      # ----------------------------------------------------------------
      # 1. SETUP & DEPENDENCIES
      # ----------------------------------------------------------------
      - name: Install dependencies & Generate Icons
        script: |
          #!/bin/bash
          set -e
          
          echo "📦 Running Flutter pub get..."
          flutter pub get
          
          # Tự động tạo Icon nếu bạn đã config trong pubspec.yaml
          echo "🎨 Generating App Icons..."
          flutter pub run flutter_launcher_icons || true

          echo "🔧 Precaching iOS tools..."
          flutter precache --ios

      # ----------------------------------------------------------------
      # 2. HACK PROJECT (QUAN TRỌNG: Gỡ bỏ yêu cầu Signing)
      # ----------------------------------------------------------------
      - name: Disable Signing & Configure Xcode Project
        script: |
          #!/bin/bash
          set -e
          
          echo "🏗️ Generating Xcode project structure..."
          # Chạy lệnh build ảo để Flutter tạo ra các file Pods và xcodeproj
          flutter build ios --release --no-codesign || true
          
          PBXPROJ="ios/Runner.xcodeproj/project.pbxproj"
          
          if [ -f "$PBXPROJ" ]; then
              echo "🔒 Hacking project.pbxproj to remove signing requirements..."
              cp "$PBXPROJ" "$PBXPROJ.backup"
              
              # Dùng lệnh sed để xóa sạch các dòng yêu cầu chứng chỉ trong file cấu hình Xcode
              sed -i '' 's/CODE_SIGN_IDENTITY = .*;/CODE_SIGN_IDENTITY = "";/g' "$PBXPROJ"
              sed -i '' 's/DEVELOPMENT_TEAM = .*;/DEVELOPMENT_TEAM = "";/g' "$PBXPROJ"
              sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/g' "$PBXPROJ"
              sed -i '' 's/ENABLE_BITCODE = YES;/ENABLE_BITCODE = NO;/g' "$PBXPROJ"
              
              echo "✅ Code signing disabled successfully!"
          else
              echo "❌ Error: project.pbxproj not found!"
              exit 1
          fi

      # ----------------------------------------------------------------
      # 3. BUILD ARCHIVE (UNSIGNED)
      # ----------------------------------------------------------------
      - name: Build XCArchive via xcodebuild
        script: |
          #!/bin/bash
          set -e
          
          cd ios
          
          echo "🔄 Updating Pods (Required for shared_preferences)..."
          pod repo update --silent
          pod install
          
          echo "🚀 Building Runner.xcarchive..."
          # Build native với cờ cấm Signing
          xcodebuild \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -archivePath ../build/Runner.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            ENABLE_BITCODE=NO \
            COMPILER_INDEX_STORE_ENABLE=NO \
            archive
          
          cd ..

      # ----------------------------------------------------------------
      # 4. PACKAGE IPA (MANUAL PAYLOAD)
      # ----------------------------------------------------------------
      - name: Package Payload into IPA
        script: |
          #!/bin/bash
          set -e
          
          APP_PATH="build/Runner.xcarchive/Products/Applications/Runner.app"
          
          if [ ! -d "$APP_PATH" ]; then
              echo "❌ Error: Runner.app not found. Build failed."
              exit 1
          fi
          
          echo "📦 Packaging IPA manually for Sideloadly..."
          cd build/Runner.xcarchive/Products/Applications
          
          # Tạo folder Payload chuẩn của Apple
          mkdir -p Payload
          cp -r Runner.app Payload/
          
          # Zip lại thành file .ipa
          # Flag -y quan trọng để giữ Symlinks
          zip -r -y SienCa_Unsigned.ipa Payload/
          
          # Move ra ngoài để Artifacts lấy được
          mv SienCa_Unsigned.ipa ../../../../SienCa_Unsigned.ipa
          
          echo "🎉 IPA Created: SienCa_Unsigned.ipa"

    # ----------------------------------------------------------------
    # 5. OUTPUT
    # ----------------------------------------------------------------
    artifacts:
      - SienCa_Unsigned.ipa